// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPdf93MPkAuY2lljAh00BQCwZHDXxtyhk',
    appId: '1:802136958785:web:76117eb8a9e4fc5b7e63c0',
    messagingSenderId: '802136958785',
    projectId: 'mynotesrtes',
    authDomain: 'mynotesrtes.firebaseapp.com',
    storageBucket: 'mynotesrtes.appspot.com',
    measurementId: 'G-TN37BEY63F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKLg1JKzbRGA3O7BQn_Lywvh7ojyZLGmI',
    appId: '1:802136958785:android:8c46ab241420611f7e63c0',
    messagingSenderId: '802136958785',
    projectId: 'mynotesrtes',
    storageBucket: 'mynotesrtes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADAZ7c6cduyTV02-OGLg3EYNB_Q1Vt8yI',
    appId: '1:802136958785:ios:68575175101c4a697e63c0',
    messagingSenderId: '802136958785',
    projectId: 'mynotesrtes',
    storageBucket: 'mynotesrtes.appspot.com',
    iosClientId: '802136958785-hnobmm0vt0t2s4t1445bg8kam608pqcg.apps.googleusercontent.com',
    iosBundleId: 'com.tommy.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADAZ7c6cduyTV02-OGLg3EYNB_Q1Vt8yI',
    appId: '1:802136958785:ios:396b0c17e6eb24c97e63c0',
    messagingSenderId: '802136958785',
    projectId: 'mynotesrtes',
    storageBucket: 'mynotesrtes.appspot.com',
    iosClientId: '802136958785-ioihltvk1vbesrbspig2jnrkrtargd84.apps.googleusercontent.com',
    iosBundleId: 'com.tommy.mynotes.RunnerTests',
  );
}
